### ISSUE TITLE
Double Free of std::coroutine_handle

### ISSUE THREAD

**Issue by liuq** [fschuetz04/simcpp20#1]
Apparently, when using the `value_event` class the system incurs in a double free error when exiting the program (i.e., all processes have been stopped).

```
value_process(64525,0x100f6c580) malloc: *** error for object 0x600001844050: pointer being freed was not allocated
```

Unfortunately I cannot go too much in depth for debugging, but it seems that the error is related to the following destructor (and possibly to [this phenomenon](https://stackoverflow.com/questions/62981634/calling-destroy-on-a-coroutine-handle-causes-segfault)) in `event.hpp`:

```c
 class data {
  public:
    ...
    /// Destructor.
    virtual ~data() {
      for (auto &handle : handles_) {
        handle.destroy();
      }
    }
}
```

A possible workaround might be to use a `std::suspend_always` instead of a `std::suspend_never` for the `final_suspend` method, however I am not able to understand the implications for the simulation.

My system is a MacOS 12.3.1 running on Arm M1 Pro. The code has been compiled with `g++-11 (Homebrew GCC 11.2.0_3) 11.2.0`.

**Comment by liuq** [comment]
Some further inspection: having tested also on Linux (with gdb, and compiling with g++-10) it seems that is the destruction of the vector of handles, i.e.

```c
 std::vector<std::__n4861::coroutine_handle<void>, std::allocator<std::__n4861::coroutine_handle<void> > >::~vector
```

that raises the double free.

In this case the system is a Linux Ubuntu 20.04 with g++ v. 10.3.0.

**Comment by liuq** [comment]
Eureka! I'll send a PullRequest... there was the call of the superclass desctructor of value_event that apparently is un-necessary (since the superclass/subclass destructors will always be called) and which raised the issue.

**Comment by fschuetz04** [comment]
Thanks for your investigation! Looking forward to the pull request.

**Comment by fschuetz04** [comment]
Sorry for not getting back to you sooner. Please see my comments on your PR #3 . A fix for this issue is in the main branch now, please test again and close this issue if the fix works for you. Thanks for your work!
