### ISSUE TITLE
Latest changes

### ISSUE THREAD

**Issue by aromanro** [fschuetz04/simcpp20#10]
I tried the latest changes, things seem to work, then I tried your example, 'value_process'.
I think before it displayed 42, now it crashes, somewhere in event::process, on a call on resume: `promise->process_handle().resume()`.

There is a null pointer access violation, I guess that could be overcome by checking the 'address' of the handle, but I'm not sure it will entirely solve the problem.

Adding this:
```
if (!promise->process_handle().address())
        continue;
```
in the for loop before checking the promise avoids the crash, but still does not work ok, as expected, nothing is displayed.

**Comment by fschuetz04** [comment]
Thanks, I will investigate.

**Comment by fschuetz04** [comment]
I forgot to initialize `handle_` in `promise_type` of `value_event`. Should be fixed now, please verify.

**Comment by aromanro** [comment]
It's fixed! I tried both my test variants and both are working as expected.
Also the value_process now works as well, but I guess you know that already :)
