### ISSUE TITLE
Add yield

### ISSUE THREAD

**Issue by aromanro** [fschuetz04/simcpp20#12]
Just a suggestion for a possible enhancement (I'm sure you already thought of it, but just in case): It might be possible to also support yield events from coroutines.

**Comment by fschuetz04** [comment]
Right now, each process returns an event which is triggered when the process `co_returns` (or at the end of the process function). Are you suggesting that the event can be triggered multiple times and is triggered for each `co_yield` as well? Right now, events can only be triggered once. Or maybe a special function returning the next event for the next `co_yield`?

**Comment by aromanro** [comment]
Yes, something like that. It's just a suggestion.

I think it would be nice to also allow co_yield in those coroutines.

**Comment by fschuetz04** [comment]
I did some experiments with `co_yield`, but did not find a nice way to integrate it. Feel free to reopen this issue with a proposal :)
