### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by efokken-abb** [fschuetz04/simcpp20#6]
Do you know anything more about the memory leaks?

I would like to use your code but don't really know, how much I should worry about the leaks. Do they only happen at program termination, after which the OS will reclaim everything regardless or can they accumulate?
In the end, if I use your project, I'm prepared to find and fix the leaks but it's rather opaque to me right now.

**Comment by aromanro** [comment]
Could you please give an example where you noticed those memory leaks? I'm evaluating this for use in a project.

**Comment by fschuetz04** [comment]
I noticed the memory leaks when running the examples `all_of.cpp` and `machine_shop.cpp`. Basically, as long as an event is created and then triggered at some point, no leak should occur. An event which is never triggered will lead to a memory leak. In theory, this should be fixable by counting event references and cancelling events when they are no longer referenced by anything that might trigger them, but unfortunately this does not work yet.

**Comment by aromanro** [comment]
I just run those two examples, compiled with Visual C++. No memory leaks reported.

By your description, it looks like the events that remain in the priority queue are not destructed properly.
There are two types of events, `event` and `value_event`, the later derived from the former. It has an additional 'value' in it.

If there are leaks, they might be easy to fix (maybe even having the `event` destructor changed to be `virtual` fixes it).

**Comment by aromanro** [comment]
Could you please tell me why the usage of `std::vector<event_type> evs` in `simulator`'s `any_of` and `all_of` instead of `const std::vector<event_type>& evs`? I changed to have the later form and tests pass ok and examples seem to work with no issues (but I did not check them all, only compiled them).

**Comment by fschuetz04** [comment]
I don't think there is any reason for not using references in these methods, as the events are only needed during the method call.  Also I'm not sure whether passing the events as vectors is a good idea in this case in general.

**Comment by aromanro** [comment]
I did some changes and made a pull request. Maybe using smart pointers solves the issue (or maybe adds something more, in case that circular references are possible :) ). Please look at it if you have time.

There are some things passed by value when they could be passed by const reference which maybe would improve things a little, but besides that this project seems very usable and well written so I think we might use it in a project.

Thank you for making this available!

**Comment by fschuetz04** [comment]
I am working on getting rid of the memory leaks, but I am still facing issues, primarily with code like this:

```cpp
#include <cstdio>
#include "fschuetz04/simcpp20.hpp"

simcpp20::event<> a(simcpp20::simulation<> &sim) {
  printf("[%.0f] a 1\n", sim.now());
  co_await (sim.event() | sim.event());
  printf("[%.0f] a 2\n", sim.now());
}

int main() {
  simcpp20::simulation<> sim;
  a(sim);
  sim.run();
}
```

The two temporary events created in `a` only go out of scope at the end of `a`, so a reference to them is kept. The event created by the `any_of` operation is referenced by the two temporary events and by the `a`. The reference from `a` to the `any_of` event can be detected to be from a suspended process, so it can be ignored. However, the references from the temporary events cannot be ignored, because the `any_of` event might be triggered by any event referencing it. So I must somehow detect that the two temporary events will never be triggered - but I don't really know how to do that. Maybe some mechanism to store that these event references belong to a suspended process as well, so they do not count?

Overall, this results in the memory of the three events, the coroutine process, and the additional process event being leaked. Of course, I could prevent this by keeping a list of events created by the simulation, but then they can only be cleared at the end of the simulation, which doesn't sound optimal to me.

**Comment by aromanro** [comment]
Are they really leaked?
I expect them being released after main.

I get no leaks in debug mode for your example, with Visual Studio. I'll do more tests.
By the way, what's the purpose of the `awaiting_ev_` pointer? I see a lot of asserts on it but really not much functionality.

I intend to change the code to be able to have multiple waits for the same event and get all of them awaken, one way would be to replace that with an unordered_set, another would be to get rid of it altogether. If I'm not mistaken, its only usage is to throw a nullptr on resume if the event was aborted. But since handles are destroyed when aborting, is that possible to happen?

**Comment by fschuetz04** [comment]
At least for me on Linux with GCC they are leaked (according to Valgrind).

The purpose of `awaiting_ev_` is to be able to abort a process by calling `abort()` on the event returned by the process. `awaiting_ev_` points to this event associated with the process and can be used to check whether that event has been aborted in `await_resume`. For example:

```cpp
#include <cstdio>

#include "fschuetz04/simcpp20.hpp"

simcpp20::event<> a(simcpp20::simulation<> &sim) {
  printf("[%.0f] a 1\n", sim.now());
  co_return;
}

int main() {
  simcpp20::simulation<> sim;
  auto ev_a = a(sim);
  ev_a.abort();
  sim.run();
}
```

In this case, the process `a` will never be run because it is aborted before the simulation starts. However, I implemented this by throwing `nullptr` into the coroutine, which should probably replaced by simply destroying the coroutine handle (this will trigger the assert in `unhandled_exception` in debug mode.

**Comment by fschuetz04** [comment]
Regarding multiple waits for the same event: In what scenario is this not working for you? For example:

```cpp
#include <cstdio>

#include "fschuetz04/simcpp20.hpp"

simcpp20::event<> a(simcpp20::simulation<> &sim, simcpp20::event<> ev) {
  printf("[%.0f] a 1\n", sim.now());
  co_await ev;
  printf("[%.0f] a 2\n", sim.now());
}

simcpp20::event<> b(simcpp20::simulation<> &sim, simcpp20::event<> ev) {
  printf("[%.0f] b 1\n", sim.now());
  co_await ev;
  printf("[%.0f] b 2\n", sim.now());
}

int main() {
  simcpp20::simulation<> sim;
  auto ev = sim.timeout(1);
  a(sim, ev);
  b(sim, ev);
  sim.run();
}
```

One event is created, passed to two processes, and both of them are woken up at time 1. The event is copied for this, but the underlying data structure is the same for all instances. Do you want to pass the events by reference instead?

**Comment by aromanro** [comment]
Not always reported leaks are really leaks.
I currently have such situation with a project.
Using boost::tests reports leaks, while Visual Studio debug mode on the tests project does not. 
I have a workaround of boost::tests to avoid that reporting, but then if I debug the testing project I get reported leaks in Visual Studio :)

I'll do a pull request and then add an example here to see what I mean.

**Comment by aromanro** [comment]
This is something that I've done for a resemblance with the simcpp project (the one with 'Protothreads'):

```
#define OBSERVABLE_PROPERTY(TYP, NAM, VAL)                                     \
private:                                                                       \
  TYP NAM = VAL;                                                               \
																			   \
public:                                                                        \
  simcpp20::value_event<TYP> NAM##_event{sim};                                 \
  TYP get_##NAM() const {                                                      \
	return this->NAM;                                                          \
  }                                                                            \
  void set_##NAM(TYP v) {                                                      \
	this->NAM = v;                                                             \
	this->sim.schedule(this->NAM##_event);                                     \
	this->NAM##_event = simcpp20::value_event<TYP>(sim);                       \
  }


class EnvObj {
public:
  simcpp20::simulation<> &sim;


  explicit EnvObj(simcpp20::simulation<> &sim) : sim(sim) {}
  virtual ~EnvObj() = default;
};
```

And here is something (not very meaningful, just for testing), that I used:

```
class Environment : public EnvObj {
public:
  explicit Environment(simcpp20::simulation<> &sim) : EnvObj(sim) {}
  ~Environment() noexcept override = default;

  OBSERVABLE_PROPERTY(int, Packet, 0);
};



class Cable {
public:
  explicit Cable(Environment& env) 
	  : sim(env.sim), env(env)
  { 
	  Run();
  }

  simcpp20::event<> Run() 
  {
	  while (env.sim.now() < 100) {
		auto timeout = env.sim.timeout(3);
		co_await timeout;

		if (!q.empty()) 
		{
		  printf("Cable waking up and sending packet %d at %g.\n", q.front(), env.sim.now());
		  
		  int packet = getPacket();
		 
		  env.set_Packet(packet);
		} else printf("Cable waking up but has nothing to send at %g.\n", env.sim.now());
	  }
  }

  int getPacket() {
	if (q.empty())
	  return 0;

	int res = q.front();
	q.pop();
	return res;
  }

  void SendPacket(int data) { q.push(data); }
private:
  std::queue<int> q;

public:
  simcpp20::simulation<> &sim;
  Environment &env;
};

class Sender {
public:
  explicit Sender(Environment &env, Cable &cable) : sim(env.sim), cable(cable) 
  {
	Run();
  }

   simcpp20::event<> Run() {
	while (sim.now() < 100) {
	  co_await sim.timeout(5);

	  ++packet;

	  printf("Sender sending %d packet at %g.\n", packet, sim.now());
	  cable.SendPacket(packet);
	}
  }

  simcpp20::simulation<> &sim;

private:
  int packet = 0;
  Cable& cable;
};

class Receiver {
public:
  explicit Receiver(Environment &env, Cable &cable, int recvId)
	  : sim(env.sim), env(env), cable(cable), recvId(recvId) {
	Run();
  }

  simcpp20::event<> Run() {
	while (env.sim.now() < 100) {
	  int packet = 0;

	  co_await env.Packet_event;
	  packet = env.get_Packet();
	 	 
	  if (packet != 0)
		  printf("Receiver %d received %d packet at %g.\n", recvId, packet, env.sim.now());
	  else
		  printf("Odd, empty packet received by receiver %d\n", recvId);
	}
  }

  simcpp20::simulation<> &sim;
  Environment &env;
  Cable &cable;
  int recvId;
};

int main() {
  simcpp20::simulation<> sim;
  Environment env(sim);

  Cable cable(env);
  Sender sender(env, cable);
  Receiver receiver1(env, cable, 1);
  Receiver receiver2(env, cable, 2);
  Receiver receiver3(env, cable, 3);

  sim.run();
}
```

Results after the changes (the ones I expected):
```
Cable waking up but has nothing to send at 3.
Sender sending 1 packet at 5.
Cable waking up and sending packet 1 at 6.
Receiver 1 received 1 packet at 6.
Receiver 2 received 1 packet at 6.
Receiver 3 received 1 packet at 6.
Cable waking up but has nothing to send at 9.
Sender sending 2 packet at 10.
Cable waking up and sending packet 2 at 12.
Receiver 1 received 2 packet at 12.
Receiver 2 received 2 packet at 12.
Receiver 3 received 2 packet at 12.
Sender sending 3 packet at 15.
Cable waking up and sending packet 3 at 15.
Receiver 1 received 3 packet at 15.
Receiver 2 received 3 packet at 15.
Receiver 3 received 3 packet at 15.
Cable waking up but has nothing to send at 18.
Sender sending 4 packet at 20.
Cable waking up and sending packet 4 at 21.
Receiver 1 received 4 packet at 21.
Receiver 2 received 4 packet at 21.
Receiver 3 received 4 packet at 21.
Cable waking up but has nothing to send at 24.
Sender sending 5 packet at 25.
Cable waking up and sending packet 5 at 27.
Receiver 1 received 5 packet at 27.
Receiver 2 received 5 packet at 27.
Receiver 3 received 5 packet at 27.
Sender sending 6 packet at 30.
Cable waking up and sending packet 6 at 30.
Receiver 1 received 6 packet at 30.
Receiver 2 received 6 packet at 30.
Receiver 3 received 6 packet at 30.
Cable waking up but has nothing to send at 33.
Sender sending 7 packet at 35.
Cable waking up and sending packet 7 at 36.
Receiver 1 received 7 packet at 36.
Receiver 2 received 7 packet at 36.
Receiver 3 received 7 packet at 36.
Cable waking up but has nothing to send at 39.
Sender sending 8 packet at 40.
Cable waking up and sending packet 8 at 42.
Receiver 1 received 8 packet at 42.
Receiver 2 received 8 packet at 42.
Receiver 3 received 8 packet at 42.
Sender sending 9 packet at 45.
Cable waking up and sending packet 9 at 45.
Receiver 1 received 9 packet at 45.
Receiver 2 received 9 packet at 45.
Receiver 3 received 9 packet at 45.
Cable waking up but has nothing to send at 48.
Sender sending 10 packet at 50.
Cable waking up and sending packet 10 at 51.
Receiver 1 received 10 packet at 51.
Receiver 2 received 10 packet at 51.
Receiver 3 received 10 packet at 51.
Cable waking up but has nothing to send at 54.
Sender sending 11 packet at 55.
Cable waking up and sending packet 11 at 57.
Receiver 1 received 11 packet at 57.
Receiver 2 received 11 packet at 57.
Receiver 3 received 11 packet at 57.
Sender sending 12 packet at 60.
Cable waking up and sending packet 12 at 60.
Receiver 1 received 12 packet at 60.
Receiver 2 received 12 packet at 60.
Receiver 3 received 12 packet at 60.
Cable waking up but has nothing to send at 63.
Sender sending 13 packet at 65.
Cable waking up and sending packet 13 at 66.
Receiver 1 received 13 packet at 66.
Receiver 2 received 13 packet at 66.
Receiver 3 received 13 packet at 66.
Cable waking up but has nothing to send at 69.
Sender sending 14 packet at 70.
Cable waking up and sending packet 14 at 72.
Receiver 1 received 14 packet at 72.
Receiver 2 received 14 packet at 72.
Receiver 3 received 14 packet at 72.
Sender sending 15 packet at 75.
Cable waking up and sending packet 15 at 75.
Receiver 1 received 15 packet at 75.
Receiver 2 received 15 packet at 75.
Receiver 3 received 15 packet at 75.
Cable waking up but has nothing to send at 78.
Sender sending 16 packet at 80.
Cable waking up and sending packet 16 at 81.
Receiver 1 received 16 packet at 81.
Receiver 2 received 16 packet at 81.
Receiver 3 received 16 packet at 81.
Cable waking up but has nothing to send at 84.
Sender sending 17 packet at 85.
Cable waking up and sending packet 17 at 87.
Receiver 1 received 17 packet at 87.
Receiver 2 received 17 packet at 87.
Receiver 3 received 17 packet at 87.
Sender sending 18 packet at 90.
Cable waking up and sending packet 18 at 90.
Receiver 1 received 18 packet at 90.
Receiver 2 received 18 packet at 90.
Receiver 3 received 18 packet at 90.
Cable waking up but has nothing to send at 93.
Sender sending 19 packet at 95.
Cable waking up and sending packet 19 at 96.
Receiver 1 received 19 packet at 96.
Receiver 2 received 19 packet at 96.
Receiver 3 received 19 packet at 96.
Cable waking up but has nothing to send at 99.
Sender sending 20 packet at 100.
Cable waking up and sending packet 20 at 102.
Receiver 1 received 20 packet at 102.
Receiver 2 received 20 packet at 102.
Receiver 3 received 20 packet at 102.
```

Before only one receiver received the 'packet'.

**Comment by fschuetz04** [comment]
I see, so you are accessing the same event instance instead of copying events for the different processes, so this does not work right now.

**Comment by aromanro** [comment]
It works with the changes I did. I made a pull request, please take a look over it.

**Comment by fschuetz04** [comment]
@aromanro Can you please test your example with the latest commit? Thanks!

**Comment by efokken-abb** [comment]
Just for your information: I probably won't use this project in the near future, because my tasks changed in the meantime and I can't contribute to this discussion. If you want, I can close the issue now or leave it open and you can close it, as soon as you deem it apropriate. Best of luck to you!

**Comment by aromanro** [comment]
I briefly tried both my examples (the one from here and the one from the closed pull request) and they both seem to work all right.
I'll look again over the code, thanks!

**Comment by fschuetz04** [comment]
@efokken-abb Thanks, and sorry for getting this issue off-topic. I guess I will close the issue and open a new one with more information about the memory leaks :)

**Comment by efokken-abb** [comment]
> @efokken-abb Thanks, and sorry for getting this issue off-topic. I guess I will close the issue and open a new one with more information about the memory leaks :)

No worries!
